apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gcs-downloader
  namespace: cfg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcs-downloader
  template:
    metadata:
      labels:
        app: gcs-downloader
    spec:
      initContainers:
        - name: gcs-downloader
          image: google/cloud-sdk:latest
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/bash"
            - "-c"
            - |
              gcloud auth activate-service-account --key-file=/var/secrets/cfg-secret/key.json
              gsutil cp gs://bucket-zero1/cfghelm_gcp_stg-values.yaml /tmp
          volumeMounts:
            - name: cfg-secret
              mountPath: /var/secrets/cfg-secret
              readOnly: true
            - name: values-file
              mountPath: /tmp
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80 
          volumeMounts:
            - name: values-file
              mountPath: /usr/share/nginx/html
      volumes:
        - name: cfg-secret
          secret:
            secretName: cfg-secret
            defaultMode: 420
        - name: values-file
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: values-service
  namespace: cfg
spec:
  selector:
    app: gcs-downloader
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
